{
    'name': "Mantenimiento Support",
    'version': "1.0.1",
    'author': "Marco Gonzalez",
    'category': "Tools",
    'support': "marco.gonzalez@grupoalvamex.com",
    'summary': "Solicitudes de mantenimiento / Registro de ticket por sitio web",
    'description': "Solicitudes de mantenimiento / Registro de ticket por sitio web",
    'license':'LGPL-3',
    'data': [
        'data/ir.module.category.csv',
        'data/res.groups.xml',
        'views/website_support_ticket_templates.xml',
        'views/website_support_ticket_compose_views.xml',
        'views/website_support_ticket_close_views.xml',
        'views/website_support_ticket_views.xml',
        'views/website_support_ticket_categories_views.xml',
        'views/website_support_ticket_subcategory_views.xml',
        'views/website_support_ticket_states_views.xml',
        'views/website_support_inventory_views.xml',
        'views/reporte_mantenimiento.xml',
        'views/website_support_ticket_service_order_views.xml',
        'views/res_partner_views.xml',
        'views/res_users_views.xml',
        'views/website_support_help_groups_views.xml',
        'views/website_support_help_page_views.xml',
        'views/website_support_ticket_priority_views.xml',
        'views/website_support_warehouse_views.xml',
        'views/mantenimiento_tipo_views.xml',
        'views/res_company_views.xml',
        'views/website_support_settings_views.xml',
        'views/website_support_ticket_department_views.xml',
        'views/website_support_ticket_preventive_views.xml',
        'views/menus.xml',
        'data/website.support.ticket.states.xml',
        'data/website.menu.csv',
        'data/website.support.ticket.priority.xml',
        'data/website.support.settings.xml',
        'data/website.support.department.role.csv',
        'data/website.support.ticket.approval.xml',
        'data/mantenimiento.tipo.xml',
        'data/mantenimiento.preventiva.xml',
        'data/mantenimiento.categoria.xml',
        'security/ir.model.access.csv',
    ],
    'demo': [],
    'depends': ['mail','web', 'website',
        'purchase', 'contacts','web_readonly_bypass'],
    #'images':[
    #    'static/description/3.jpg',
    #    'static/description/1.jpg',
    #    'static/description/2.jpg',
    #    'static/description/4.jpg',
    #    'static/description/5.jpg',
    #    'static/description/6.jpg',
    #],
    'installable': True,
}